### ISSUE TITLE
[BUG] After closing the cURL-handle it can not be used with curl_error

### ISSUE THREAD

**Issue by estebanthebad** [seven-io/php-client#1]
https://github.com/sms77io/php-client/blob/ec0339d72bcdfa930b80ab1c8cd2e2838b944d46/src/BaseClient.php#L97-L102

PHP 7.4.24

curl_error needs to be called before curl_close. 

Or the warning 'curl_error(): supplied resource is not a valid cURL handle resource' and subsequently an exception 'Uncaught Error: Wrong parameters for UnexpectedValueException' (as it is not a string) is thrown.

It seems you put the code upside down in that spot. 'Found that bug when curl wanted to complain about missing SSL klimborium.

**Comment by estebanthebad** [comment]
Btw. please also add the error code, like so:
```
 throw new UnexpectedValueException(curl_error($ch), curl_errno($ch)); 
```
Thanks!

**Comment by matthiez** [comment]
thanks for reporting @estebanthebad will fix asap in the next release but im quite busy with other stuff atm - feel free to open a pull request on your own though :)
