### ISSUE TITLE
[BUG] Lookup Format - Invalid Return Type - Exception TypeError

### ISSUE THREAD

**Issue by justpilot** [seven-io/php-client#11]
**Input data:**

number: +16515672202

```
POST https://gateway.seven.io/api/lookup
host: gateway.seven.io
content-length: 53
x-api-key: ...1dfD45
sentwith: php-api
content-type: application/json
accept: application/json

{"json":null,"type":"format","number":"+16515672202"}
```

```
Content-Type: application/json
X-sms77-trace-id: 5577E9B5a64a657fd10D6B331010F955

{"success":true,"national":"(651) 308-2712","international":"+16513082712","international_formatted":"+1 651-308-2712","country_name":"United States of America","country_code":1,"country_iso":"US","carrier":"","network_type":"mobile"}
```

**Bug**: country_code type is an INT.
**Should**: country_code type should be a STRING.

This bug results in:

`Exception TypeError: "Cannot assign int to property Seven\Api\Response\Lookup\LookupFormat::$countryCode of type string" at /vendor/seven.io/api/src/Response/Lookup/LookupFormat.php line 19`

https://github.com/seven-io/php-client/blob/6458cf9d03b6f5999fd7ad55dd75a94ce9b92429/src/Response/Lookup/LookupFormat.php#L19C1-L19C12

**Comment by cl77** [comment]
Thanks, we have just fixed that bug.
