### ISSUE TITLE
[BUG] Uncaught Exception TypeError: "Cannot assign null to property Seven\Api\Response\Lookup\LookupFormat::$countryIso of type string" /vendor/seven.io/api/src/Response/Lookup/LookupFormat.php line 18

### ISSUE THREAD

**Issue by justpilot** [seven-io/php-client#13]
`Uncaught Exception TypeError: "Cannot assign null to property Seven\Api\Response\Lookup\LookupFormat::$countryIso of type string" at /www/htdocs/w00d4062/login.faceshop.de/vendor/seven.io/api/src/Response/Lookup/LookupFormat.php line 18`

```
{
  "success": false,
  "national": "",
  "international": "+",
  "international_formatted": "",
  "country_name": null,
  "country_code": false,
  "country_iso": null,
  "carrier": null,
  "network_type": null
}
```

Please make `$countryIso` nullable. Also check the other class properties.
Please add a test with '000' as phone number parameter for example.

**Comment by matthiez** [comment]
fixed in [v5](https://github.com/seven-io/php-client/releases/tag/v5.0.0)
