### ISSUE TITLE
[BUG] Webhooks SMS status change (DLR) - empty data object

### ISSUE THREAD

**Issue by justpilot** [seven-io/php-client#14]
Occasionally receiving **empty POST Data** from the correct Server IP (195.201.160.143).

```
http_method: POST
ip: 195.201.160.143
$_POST: []
```

Result:

`E_WARNING: Undefined property: stdClass::$foreign_id`

**Comment by cl77** [comment]
Did you already check the Debugger in your account? Please also provide me the trace ID.

**Comment by justpilot** [comment]
Track ID: 38023163

**Comment by cl77** [comment]
Seems we've had a bug here. Just fixed that. Thanks!
