### ISSUE TITLE
[BUG] Faulty cast to boolean

### ISSUE THREAD

**Issue by estebanthebad** [seven-io/php-client#2]
Hey again!

https://github.com/sms77io/php-client/blob/ec0339d72bcdfa930b80ab1c8cd2e2838b944d46/src/Response/Sms.php#L19

`(bool)"false"` does not evaluate to the boolean value `FALSE` but to the boolean value `TRUE`.

https://www.php.net/manual/en/language.types.boolean.php

;)
Cheers!

**Comment by matthiez** [comment]
thanks for reporting @estebanthebad will fix asap in the next release but im quite busy with other stuff atm - feel free to open a pull request on your own though :)

**Comment by cl77** [comment]
Fixed with [latest release](https://github.com/seven-io/php-client/releases/tag/v4.0.1).
