### ISSUE TITLE
[BUG] When you pass an empty string to setFrom() the message will not be sent but the costs are deducted from the account.

### ISSUE THREAD

**Issue by estebanthebad** [seven-io/php-client#4]

**Comment by cl77** [comment]
This is not a bug. See more here: https://help.seven.io/en/set-sender-id

> Our system automatically replaces invalid or missing sender IDs. If you do not specify a sender, the setting for the [default sender](https://help.seven.io/en/set-sender-id#create-default-sender) from your account will be used, if available.
